services:
  # Development services
  postgres:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: z_legend_game
      POSTGRES_PASSWORD: "iMtRdthVopf1oR_ZbLZpsGPWnO_65-c5"
    volumes:
      - z_legend_game_data:/var/lib/postgresql/data


  # Test services
  postgres_test:
    image: ghcr.io/serverpod/postgres:16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: z_legend_game_test
      POSTGRES_PASSWORD: "7_TzkCozI9ajrR0_F2ZrrbFuw0gq6SfH"
    volumes:
      - z_legend_game_test_data:/var/lib/postgresql/data


volumes:
  z_legend_game_data:
  z_legend_game_test_data:
