"""
Measure the Pipeline 1 slicer against the Flare answer key.

Runs ``slice_spritesheet`` on game-assets/grassland_tiles.png and matches the
chips one-to-one with the Flare rectangles (greedy, highest IoU first, match
at IoU >= 0.5). Fully transparent Flare rectangles are left out of the
answer key: no slicer can find them.

Two answer keys:
  * padded cells: the Flare rectangles as defined. Many are padded cells
    (a small shrub sits in a 64 x 64 box), so a tight contour chip around
    the right sprite can still miss the IoU threshold.
  * tight boxes: each Flare rectangle shrunk to the bounding box of its
    opaque pixels (alpha > 0), so padding does not hide correct detections.

Writes asset_packs/grassland_full/slicer_report.md.

Run from ``backend/``:  python tools/evaluate_slicer.py
"""
from __future__ import annotations

import dataclasses
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image

BACKEND_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BACKEND_DIR.parent
sys.path.insert(0, str(BACKEND_DIR))

from pipeline.ingestion import slicer  # noqa: E402
from pipeline.ingestion.flare import FlareTile, parse_flare_definition  # noqa: E402

SHEET = REPO_ROOT / "game-assets" / "grassland_tiles.png"
DEFINITION = REPO_ROOT / "game-assets" / "grassland_tiles.flare_v0.15_tilesetdef.txt"
REPORT = BACKEND_DIR / "asset_packs" / "grassland_full" / "slicer_report.md"
MATCH_IOU = 0.5


@dataclass
class Evaluation:
    chips: list[slicer.Chip]
    truth: list[FlareTile]
    empty: list[FlareTile]
    matches: list[tuple[int, int, float]]  # (chip index, truth index, iou)

    @property
    def precision(self) -> float:
        return len(self.matches) / len(self.chips) if self.chips else 0.0

    @property
    def recall(self) -> float:
        return len(self.matches) / len(self.truth) if self.truth else 0.0


def tight_box(alpha: np.ndarray, t: FlareTile) -> FlareTile:
    """``t`` shrunk to the bounding box of its opaque pixels (alpha > 0)."""
    ys, xs = np.nonzero(alpha[t.y : t.y + t.h, t.x : t.x + t.w] > 0)
    x0, y0 = int(xs.min()), int(ys.min())
    return dataclasses.replace(
        t, x=t.x + x0, y=t.y + y0, w=int(xs.max()) - x0 + 1, h=int(ys.max()) - y0 + 1,
    )


def evaluate(
    sheet: Path = SHEET, definition: Path = DEFINITION, answer_key: str = "padded",
) -> Evaluation:
    """``answer_key``: ``"padded"`` (Flare rectangles) or ``"tight"`` (opaque boxes)."""
    if answer_key not in ("padded", "tight"):
        raise ValueError(f"unknown answer key: {answer_key}")
    alpha = np.array(Image.open(sheet).convert("RGBA"))[:, :, 3]
    flare = parse_flare_definition(definition)
    truth = [t for t in flare if alpha[t.y : t.y + t.h, t.x : t.x + t.w].any()]
    empty = [t for t in flare if t not in truth]
    if answer_key == "tight":
        truth = [tight_box(alpha, t) for t in truth]
    chips = slicer.slice_spritesheet(sheet)
    return Evaluation(chips, truth, empty, _match(chips, truth))


def _match(chips: list[slicer.Chip], truth: list[FlareTile]) -> list[tuple[int, int, float]]:
    pairs = sorted(
        (
            (slicer.iou(c.rect, t.rect), ci, ti)
            for ci, c in enumerate(chips)
            for ti, t in enumerate(truth)
        ),
        reverse=True,
    )
    used_chips, used_truth, matches = set(), set(), []
    for score, ci, ti in pairs:
        if score < MATCH_IOU:
            break
        if ci in used_chips or ti in used_truth:
            continue
        used_chips.add(ci)
        used_truth.add(ti)
        matches.append((ci, ti, score))
    return matches


def report(padded: Evaluation, tight: Evaluation) -> str:
    evs = (("Padded cells", padded), ("Tight boxes", tight))

    def row(label: str, value) -> str:
        return f"| {label} | " + " | ".join(value(ev) for _, ev in evs) + " |"

    def by_strategy(items) -> str:
        counts = Counter(items)
        return f"contour {counts['contour']}, grid {counts['grid']}"

    lines = [
        "# Slicer report: grassland_tiles.png vs. the Flare definition",
        "",
        "Generated by `tools/evaluate_slicer.py`. Chips from `pipeline/ingestion/slicer.py` are",
        f"matched one-to-one with the answer key rectangles (greedy, highest IoU first, IoU >= {MATCH_IOU}).",
        f"{len(padded.empty)} fully transparent Flare rectangles are not in the answer key:",
        ", ".join(f"{t.section} {t.flare_id}" for t in padded.empty) + ".",
        "",
        "Two answer keys:",
        "",
        "* **Padded cells:** the Flare rectangles as defined. Many are padded cells (a small shrub",
        "  sits in a 64 x 64 box), while contour chips hug the opaque pixels, so a sprite can be",
        "  found but still miss the IoU threshold.",
        "* **Tight boxes:** each Flare rectangle shrunk to the bounding box of its opaque pixels",
        "  (alpha > 0), so padding does not hide correct detections.",
        "",
        "## Totals",
        "",
        "| Measure | " + " | ".join(name for name, _ in evs) + " |",
        "|---|" + "---|" * len(evs),
        row("Answer key rectangles", lambda ev: str(len(ev.truth))),
        row("Chips", lambda ev: f"{len(ev.chips)} ({by_strategy([c.strategy for c in ev.chips])})"),
        row("Matches", lambda ev: (
            f"{len(ev.matches)} ({by_strategy([ev.chips[ci].strategy for ci, _, _ in ev.matches])})"
        )),
        row("**Precision**", lambda ev: f"**{ev.precision:.3f}**"),
        row("**Recall**", lambda ev: f"**{ev.recall:.3f}**"),
        row("Mean IoU of matches", lambda ev: f"{np.mean([s for _, _, s in ev.matches]):.3f}"),
        "",
    ]
    lines += _section_table("Per section: padded cells", padded, tight_chip_column=True)
    lines += [
        "**Tight chip inside:** padded rectangles that contain a contour chip. Informational only.",
        "",
    ]
    lines += _section_table("Per section: tight boxes", tight, tight_chip_column=False)
    lines += [
        "## Settings",
        "",
        f"Alpha threshold > {slicer.ALPHA_THRESHOLD}, dilation {slicer.DILATE_PX} px, "
        f"minimum component area {slicer.MIN_AREA} px, grid fallback for components at least "
        f"{slicer.MERGED_MIN_WIDTH} px wide or {slicer.MERGED_MIN_HEIGHT} px tall "
        f"(64 x 32 cells, minimum fill {slicer.GRID_MIN_FILL:.0%}). The dilation was chosen on the",
        "padded-cell answer key (0 px: precision 0.419, 1 px: 0.426, 2 px: 0.350, same or lower",
        "recall), so these numbers are optimistic for other spritesheets.",
        "",
    ]
    return "\n".join(lines)


def _section_table(title: str, ev: Evaluation, tight_chip_column: bool) -> list[str]:
    matched_truth = {ti: (ci, s) for ci, ti, s in ev.matches}
    sections: dict[str, list[int]] = {}
    for ti, t in enumerate(ev.truth):
        sections.setdefault(t.section, []).append(ti)

    header = "| Section | Rects | Found | Recall | Mean IoU | Found by |"
    rule = "|---|---:|---:|---:|---:|---|"
    if tight_chip_column:
        header += " Tight chip inside |"
        rule += "---:|"
    lines = [f"## {title}", "", header, rule]
    for section, indices in sections.items():
        found = [matched_truth[ti] for ti in indices if ti in matched_truth]
        strategies = Counter(ev.chips[ci].strategy for ci, _ in found)
        mean_iou = f"{np.mean([s for _, s in found]):.2f}" if found else "-"
        line = (
            f"| {section} | {len(indices)} | {len(found)} | {len(found) / len(indices):.2f} "
            f"| {mean_iou} | {', '.join(f'{k} {v}' for k, v in sorted(strategies.items())) or '-'} |"
        )
        if tight_chip_column:
            line += f" {sum(1 for ti in indices if _has_tight_chip(ev, ev.truth[ti]))} |"
        lines.append(line)
    lines.append("")
    return lines


def _has_tight_chip(ev: Evaluation, t: FlareTile) -> bool:
    x, y, w, h = t.rect
    return any(
        c.strategy == "contour"
        and c.rect[0] >= x and c.rect[1] >= y
        and c.rect[0] + c.rect[2] <= x + w and c.rect[1] + c.rect[3] <= y + h
        for c in ev.chips
    )


def main() -> None:
    padded, tight = evaluate(answer_key="padded"), evaluate(answer_key="tight")
    REPORT.write_text(report(padded, tight), encoding="utf-8")
    for name, ev in (("padded cells", padded), ("tight boxes", tight)):
        print(f"{name}: precision {ev.precision:.3f}, recall {ev.recall:.3f}, "
              f"{len(ev.matches)} matches, {len(ev.chips)} chips, {len(ev.truth)} rects")
    print(f"-> {REPORT}")


if __name__ == "__main__":
    main()
